Capstone/Controllers/UtentiController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Capstone.Models;

namespace Capstone.Controllers
{
    public class UtentiController : Controller
    {
        private ModelDbContext db = new ModelDbContext();

        public ActionResult MyProfile()
        {
            // Verifica se l'utente è autenticato
            if (!User.Identity.IsAuthenticated)
            {
                // Se l'utente non è autenticato, reindirizza alla pagina di accesso
                return RedirectToAction("Login", "Account");
            }

            // Ottieni l'IDUtente dell'utente loggato
            string username = User.Identity.Name;
            var utente = db.Utenti.FirstOrDefault(u => u.Username == username);

            if (utente == null)
            {
                // Se l'utente non viene trovato nel database, gestisci l'errore
                return HttpNotFound();
            }

            // Passa i dettagli dell'utente alla vista per visualizzarli
            return View(utente);
        }

        // GET: Utenti
        public ActionResult Index()
        {
            return View(db.Utenti.ToList());
        }

        // Azione per mostrare il numero totale di utenti nel database
        [HttpGet]
        public ActionResult GetTotalUsers()
        {
            // Recupera il numero totale di utenti dal database
            var totalUsers = db.Utenti.Count();
            return Json(totalUsers, JsonRequestBehavior.AllowGet);
        }
        // GET: Utenti/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utenti utenti = db.Utenti.Find(id);
            if (utenti == null)
            {
                return HttpNotFound();
            }
            return View(utenti);
        }

        // GET: Utenti/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Utenti/Create
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdUtente,Email,Username,Password,FotoUtente,IsArtista,Ruolo")] Utenti utenti)
        {
            if (ModelState.IsValid)
            {
                db.Utenti.Add(utenti);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(utenti);
        }

        // GET: Utenti/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utenti utenti = db.Utenti.Find(id);
            if (utenti == null)
            {
                return HttpNotFound();
            }
            var cookie = new HttpCookie("Avatar", utenti.FotoUtente);
            Response.Cookies.Add(cookie);
            return View(utenti);
        }

        // POST: Utenti/Edit/5
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, [Bind(Include = "IdUtente,Email,Username")] Utenti utenti, string newPassword, string confirmNewPassword, HttpPostedFileBase uploadImage)
        {
            ModelState.Remove("Password");
            if (id != utenti.IdUtente)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (newPassword != confirmNewPassword)
            {
                ModelState.AddModelError("ConfirmNewPassword", "Le password non corrispondono");
            }

            if (ModelState.IsValid)
            {
                if (uploadImage != null && uploadImage.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(uploadImage.FileName);
                    var filePath = Path.Combine(Server.MapPath("~/Content/Images/Utenti"), fileName);
                    uploadImage.SaveAs(filePath);
                    utenti.FotoUtente = fileName; // Aggiorna il percorso della foto solo se una nuova è stata caricata
                }

                if (!string.IsNullOrWhiteSpace(newPassword))
                {
                    // Se è stata inserita una nuova password e confermata correttamente, criptala
                    utenti.Password = HashPassword(newPassword);
                }
                else
                {
                    // Se non è stata inserita una nuova password, non aggiornare il campo password
                    db.Entry(utenti).Property(x => x.Password).IsModified = false;
                }

                db.Entry(utenti).State = EntityState.Modified;
                db.SaveChanges();

                // Aggiorna il cookie Avatar con il nuovo percorso dell'immagine dell'utente
                Response.Cookies["Avatar"].Value = utenti.FotoUtente;

                TempData["success"] = "Profilo modificato con successo!";

                return RedirectToAction("MyProfile");
            }
            
            return View(utenti);
        }



        // GET: Utenti/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utenti utenti = db.Utenti.Find(id);
            if (utenti == null)
            {
                return HttpNotFound();
            }
            return View(utenti);
        }

        // POST: Utenti/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Utenti utenti = db.Utenti.Find(id);
            db.Utenti.Remove(utenti);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        private bool VerifyPasswordHash(string password, string storedHash)
        {
            return BCrypt.Net.BCrypt.Verify(password, storedHash);
        }

        // questo metodo fa lhas della password
        private string HashPassword(string password)
        {
            return BCrypt.Net.BCrypt.HashPassword(password);
        }

        //Metodo per generare l'indirizzo del wallet per l'utente
        public ActionResult GenerateWallet()
        {
            // Ottenere l'ID dell'utente loggato
            string username = User.Identity.Name;
            var utente = db.Utenti.FirstOrDefault(u => u.Username == username);

            if (utente != null)
            {
                // Generare l'indirizzo del wallet
                string walletAddress = Guid.NewGuid().ToString();

                //Crea un nuovo wallet per l'utente
                var newWallet = new Wallets
                {
                    IdUtente = utente.IdUtente,
                    Address = walletAddress,
                    Saldo = 0 // Imposta il saldo del nuovo wallet a 0
                };

                // Aggiungere il nuovo wallet all'utente nel database
                db.Wallets.Add(newWallet);
                db.SaveChanges();

                // Output di debug per verificare che il wallet sia stato creato correttamente
                System.Diagnostics.Debug.WriteLine("Nuovo wallet creato per l'utente con ID: " + utente.IdUtente + ", indirizzo del wallet: " + walletAddress);

                TempData["success"] = "Wallet creato con successo!";

                // Reindirizza all'azione successiva o restituisci una vista opportuna
                return RedirectToAction("MyProfile");
            }
            else
            {
                TempData["error"] = "Utente non trovato!";
                // Se l'utente non è valido, gestisci l'errore o reindirizza
                return RedirectToAction("Login", "Account");
            }
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Capstone/Controllers/WalletsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Capstone.Models;

namespace Capstone.Controllers
{
    public class WalletsController : Controller
    {
        private ModelDbContext db = new ModelDbContext();

        // GET: Wallets
        public ActionResult Index()
        {
            var wallets = db.Wallets.Include(w => w.Utenti);
            return View(wallets.ToList());
        }

        // GET: Wallets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Wallets wallets = db.Wallets.Find(id);
            if (wallets == null)
            {
                return HttpNotFound();
            }
            return View(wallets);
        }

        // GET: Wallets/Create
        public ActionResult Create()
        {
            ViewBag.IdUtente = new SelectList(db.Utenti, "IdUtente", "Email");
            return View();
        }

        // POST: Wallets/Create
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdWallet,IdUtente,Address,Saldo")] Wallets wallets)
        {
            if (ModelState.IsValid)
            {
                db.Wallets.Add(wallets);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdUtente = new SelectList(db.Utenti, "IdUtente", "Email", wallets.IdUtente);
            return View(wallets);
        }

        // GET: Wallets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Wallets wallets = db.Wallets.Find(id);
            if (wallets == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdUtente = new SelectList(db.Utenti, "IdUtente", "Email", wallets.IdUtente);
            return View(wallets);
        }

        // POST: Wallets/Edit/5
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdWallet,IdUtente,Address,Saldo")] Wallets wallets)
        {
            if (ModelState.IsValid)
            {
                db.Entry(wallets).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdUtente = new SelectList(db.Utenti, "IdUtente", "Email", wallets.IdUtente);
            return View(wallets);
        }

        // GET: Wallets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Wallets wallets = db.Wallets.Find(id);
            if (wallets == null)
            {
                return HttpNotFound();
            }
            return View(wallets);
        }

        // POST: Wallets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Wallets wallets = db.Wallets.Find(id);
            db.Wallets.Remove(wallets);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult MyWallet()
        {
            // Ottenere l'ID dell'utente loggato
            string username = User.Identity.Name;
            var utente = db.Utenti.FirstOrDefault(u => u.Username == username);

            if (utente != null)
            {
                // Ottenere il wallet dell'utente
                var wallet = utente.Wallets.FirstOrDefault();

                if (wallet != null)
                {
                    // Passa i dettagli del wallet alla vista per visualizzarli
                    return View(utente);
                }
            }

            // Se l'utente non ha un wallet, gestisci l'errore
            return RedirectToAction("Login", "Account");
        }

        [HttpPost]
        public ActionResult ProcessTransaction(decimal amount, string type)
        {
            // Ottenere l'ID dell'utente loggato
            string username = User.Identity.Name;
            var utente = db.Utenti.FirstOrDefault(u => u.Username == username);

            if (utente != null)
            {
                // Ottenere il wallet dell'utente
                var wallet = utente.Wallets.FirstOrDefault();

                if (wallet != null)
                {
                    // Effettuare operazioni di deposito o prelievo
                    if (type == "Deposito")
                    {
                        wallet.Saldo += amount;
                    }
                    else if (type == "Prelievo" && wallet.Saldo >= amount)
                    {
                        wallet.Saldo -= amount;
                    }
                    else if (type == "Acquisto" && wallet.Saldo >= amount)
                    {
                        wallet.Saldo -= amount;
                    }
                    else if (type == "Vendita")
                    {
                        wallet.Saldo += amount;
                    }
                    else
                    {
                        // Gestire il caso in cui il saldo non sia sufficiente per il prelievo
                        TempData["error"] = "Saldo non sufficiente per il prelievo.";
                        return RedirectToAction("MyWallet");
                    }

                    // Aggiungere un'operazione al wallet
                    var operazione = new Operazioni
                    {
                        IdUtente = utente.IdUtente,
                        IdWallet = wallet.IdWallet,
                        Tipo = type,
                        Importo = amount,
                        DataOperazione = DateTime.Now
                    };
                    db.Operazioni.Add(operazione);
                    db.SaveChanges();

                    // Imposta il messaggio di successo
                    TempData["success"] = "Operazione completata con successo.";

                    // Reindirizza all'azione MyWallet
                    return RedirectToAction("MyWallet");
                }
            }

            // Se l'utente o il wallet non sono validi, reindirizza all'azione di login
            return RedirectToAction("Login", "Account");
        }

        // Azione per recuperare il saldo del wallet dell'utente Admin
        public ActionResult GetAdminWalletBalance()
        {
            // Recupera l'utente admin dal database
            var admin = db.Utenti.FirstOrDefault(u => u.Ruolo == "admin");

            if (admin != null)
            {
                // Recupera il wallet dell'utente admin
                var adminWallet = db.Wallets.FirstOrDefault(w => w.IdUtente == admin.IdUtente);

                if (adminWallet != null)
                {
                    // Restituisce il saldo del wallet dell'utente admin
                    return Json(adminWallet.Saldo, JsonRequestBehavior.AllowGet);
                }
            }

            // Se non è stato possibile recuperare il saldo del wallet dell'utente admin, restituisci 0 come valore di default
            return Json(0, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Capstone/Views/Utenti/Create.cshtml
@model Capstone.Models.Utenti

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Utenti</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FotoUtente, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FotoUtente, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FotoUtente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsArtista, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsArtista)
                    @Html.ValidationMessageFor(model => model.IsArtista, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ruolo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ruolo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ruolo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Capstone/Views/Utenti/Delete.cshtml
@model Capstone.Models.Utenti

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Utenti</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FotoUtente)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FotoUtente)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsArtista)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsArtista)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ruolo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ruolo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Capstone/Views/Utenti/Details.cshtml
@model Capstone.Models.Utenti

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Utenti</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FotoUtente)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FotoUtente)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsArtista)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsArtista)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ruolo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ruolo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdUtente }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Capstone/Views/Utenti/Edit.cshtml
@model Capstone.Models.Utenti

@{
    ViewBag.Title = "Edit";
}

<div class="container mt-5 py-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h2 class="text-white">Modifica Profilo</h2>
            @using (Html.BeginForm("Edit", "Utenti", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal text-white">
                    <hr class="w-75" />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.IdUtente)

                    <div class="form-group mb-3">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group mb-3">
                        @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <!-- Campo per la nuova password -->
                    <div class="form-group mb-3">
                        <div class="col-md-8">
                            <label for="newPassword" class="control-label">Nuova Password</label>
                            <input type="password" id="newPassword" name="newPassword" class="form-control" />
                            <span toggle="#newPassword" class="fa fa-fw fa-eye field-icon toggle-password"></span>
                        </div>

                    </div>
                    <div class="form-group mb-3">
                        <div class="col-md-8">
                            <label for="confirmNewPassword" class="control-label">Conferma Nuova Password</label>
                            <input type="password" id="confirmNewPassword" name="confirmNewPassword" class="form-control" />
                            <span toggle="#confirmNewPassword" class="fa fa-fw fa-eye field-icon toggle-password"></span>
                        </div>

                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.FotoUtente, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @if (!string.IsNullOrEmpty(Model.FotoUtente))
                            {
                                <img src="@Url.Content("~/Content/Images/Utenti/" + Model.FotoUtente)" alt="Foto Utente" class="img-thumbnail me-3" width="150" />
                            }
                            <input type="file" name="uploadImage" />
                        </div>
                    </div>

                    <!-- Bottone di submit -->
                    <div class="form-group mt-3">
                        <div class="col-md-offset-4 col-md-8 d-flex justify-content-center">
                            <input type="submit" value="Crea" class="btn btn-custom me-3" />
                            @Html.ActionLink("Torna al Profilo", "MyProfile", null, new { @class = "btn btn-secondary" })
                        </div>
                    </div>
                </div>
            }
        </div>

    </div>


</div>

Capstone/Views/Utenti/MyProfile.cshtml
@model Capstone.Models.Utenti

@{
    ViewBag.Title = "Il mio Profilo";
}

@Html.Partial("_Notification")

<div class="container mt-5 py-5">
    <div class="row justify-content-center">
        <div class="col-md-10 mt-5 pt-5">
            <div class="bg-light row shadow mb-5 rounded">
                <div class="col-sm-4 bg-info rounded-start">
                    <div class="card-body text-center text-white pb-3">
                        @if (!string.IsNullOrEmpty(Model.FotoUtente))
                        {
                            <img src="~/Content/Images/Utenti/@Model.FotoUtente" alt="Foto Profilo" class="rounded-circle mb-3 mt-5" height="150">
                        }
                        else
                        {
                            <img src="https://api.dicebear.com/8.x/bottts/svg?seed=Zoe" alt="avatar" height="150" class="rounded-circle mb-3 mt-5" style="object-fit:cover" />
                        }
                        <h2 class="fw-bold mt-3">@Model.Username</h2>
                        @if (Model.Wallets.Any())
                        {
                            <p>Wallet: @Model.Wallets.First().Address</p>
                        }
                        else
                        {
                            @Html.ActionLink("Genera Wallet", "GenerateWallet", null, new { @class = "btn btn-primary", id = "generateWalletBtn" })
                        }
                        <a href="@Url.Action("Edit", new { id = Model.IdUtente })" class="btn">
                            <i class="bi bi-pencil-square fs-2 text-white"></i>
                        </a>
                    </div>
                </div>
                <div class="col-sm-8 bg-white rounded-end">
                    <h3 class="mt-3 text-center ">Informazioni</h3>
                    <hr class="text-primary mt-0 w-25 text-center m-auto" />
                    <div class="row mt-5">
                        <div class="col-sm-6">
                            <p class="fw-bold">Username:</p>
                            <h6 class="text-muted">@Model.Username</h6>
                        </div>
                        <div class="col-sm-6">
                            <p class="fw-bold">Email:</p>
                            <h6 class="text-muted">@Model.Email</h6>
                        </div>
                    </div>
                    <hr class="text-primary" />
                    <h3 class="mt-5 text-center">Link Utili</h3>
                    <hr class="text-primary mt-0 w-25 text-center m-auto" />
                    <ul class="list-unstyled d-flex justify-content-between mt-4">
                        <li class="text-center">
                            <span class="d-block fw-bold mb-1">Il mio Wallet</span>
                            <a href="@Url.Action("MyWallet", "Wallets")" class="d-block"><img src="~/Content/Images/wallet.png" height="50" class="mx-auto" /></a>
                        </li>
                        <li class="text-center">
                            <span class="d-block fw-bold mb-1">Le mie Collezioni</span>
                            <a href="@Url.Action("Index", "Collezioni")" class="d-block"><img src="~/Content/Images/collections.png" height="50" class="mx-auto" /></a>
                        </li>
                        <li class="text-center">
                            <span class="d-block fw-bold mb-1">I miei NFT</span>
                            <a href="@Url.Action("MyNFTS", "NFTs")" class="d-block"><img src="~/Content/Images/nft.png" height="50" class="mx-auto" /></a>
                        </li>
                    </ul>
                    <hr class="text-primary" />
                </div>
            </div>
        </div>
    </div>
</div>